# Generated by Django 2.2.1 on 2019-05-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
